os:
  - linux
  - osx

language: go
sudo: false

go:
  - tip
  - 1.9
script:
  - go test -race ./...
  - go test ./... -bench .
notifications:
  email:
    - tiago4orion@gmail.com
    - tiagokatcipis@gmail.com
    - vitorarins@gmail.com